image:
  repository: ghcr.io/anthu2708/fraud-detection/scoring
  tag: 1ee34c2c6095b8e82e12bf7ca4ecbc82f56eca0c

imagePullSecrets:
  - name: ghcr-secret

env:
  KAFKA_BOOTSTRAP: "kafka:9092"
  MODEL_PATH: "/app/models/isolation_forest_v2.pkl"
  MODEL_VERSION: "v2"
  PYTHONUNBUFFERED: "1"
  METRICS_PORT: "9100"

service:
  enabled: true
  port: 9100

volumeMounts:
  - name: models
    mountPath: /app/models

volumes:
  - name: models
    hostPath:
      path: /fraud-models
