image:
  repository: ghcr.io/anthu2708/fraud-detection/producer
  tag: 1ef8aee6fc6c630847ef95062294a34bfc816a92

imagePullSecrets:
  - name: ghcr-secret

env:
  KAFKA_BOOTSTRAP: "kafka:9092"
  TX_PER_SECOND: "200"
  DATA_PATH: "/app/data/creditcard_test.csv"
  PYTHONUNBUFFERED: "1"

volumeMounts:
  - name: data
    mountPath: /app/data

volumes:
  - name: data
    hostPath:
      path: /fraud-data
