apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anthu2708/fraud-detection
    targetRevision: master
    path: helm/fraud-detection
    helm:
      valueFiles:
        - values-scoring.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
